<a href="https://colab.research.google.com/github/ppojawa/machine-learning-bootcamp/blob/main/unsupervised/02_dimensionality_reduction/03_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Podział na zbiór treningowy i testowy](#2)
4. [Standaryzacja](#3)
5. [PCA](#4)




### <a name='0'></a> Import bibliotek

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

### <a name='1'></a> Załadowanie danych

In [2]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
data = df.iloc[:, 1:]
target = df.iloc[:, 0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
target.value_counts()

2    71
1    59
3    48
Name: 0, dtype: int64

### <a name='2'></a> Podział na zbiór treningowy i testowy

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (133, 13)
X_test shape: (45, 13)


### <a name='3'></a> Standaryzacja

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]

array([[-0.1345,  0.6362,  0.0982,  0.1344,  0.3314, -1.6054, -0.7885, -1.0499, -1.366 ,  0.1711, -0.9548, -1.7457, -0.6737],
       [ 0.0516, -1.2972, -2.3766, -1.0941, -0.9379, -0.5494,  0.0123, -1.0499, -0.2402, -0.1856,  1.0506, -0.1828, -1.1217],
       [ 0.1508, -1.1954, -2.4124, -1.4013, -1.5021,  1.1239,  1.1493, -0.887 ,  1.2251,  0.1265,  0.7386,  0.8493, -0.7646],
       [-0.953 , -0.9364, -1.5517, -0.1727, -0.5148,  0.1167,  0.0222,  0.1721,  0.8677, -1.0327, -0.42  ,  0.6134, -1.3815],
       [ 0.0764, -0.6034,  0.6361, -0.4799, -0.0917,  0.2629,  0.4078, -0.6426, -0.276 , -0.3417,  0.7386, -0.1386,  1.1933]])

### <a name='4'></a> PCA

In [8]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

Wyjaśniona wariancja

In [9]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulative'] = results['explained_variance_ratio'].cumsum()
results['component'] = results.index + 1
results

explained_variance_ratio  cumulative  component
0                  0.367791    0.367791          1
1                  0.192430    0.560220          2
2                  0.114569    0.674789          3

In [10]:
fig = go.Figure(data=[go.Bar(x=results['component'], y=results['explained_variance_ratio'], name='explained variance ratio'),
                      go.Scatter(x=results['component'], y=results['cumulative'], name='cumulative explained variance')],
                layout=go.Layout(title=f'PCA - {pca.n_components_} components', width=950, template='plotly_dark'))
fig.show()

In [11]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca1', 'pca2', 'pca3', 'target'])
X_train_pca_df.head()

pca1      pca2      pca3  target
0 -2.361612  0.404109 -0.876253     3.0
1  0.408226 -2.209061 -2.439158     2.0
2  2.320553 -1.909908 -2.043833     2.0
3  0.112888 -2.267803 -0.466534     2.0
4  1.150023  0.065685 -0.039516     1.0

In [12]:
px.scatter_3d(X_train_pca_df, x='pca1', y='pca2', z='pca3', color='target', template='plotly_dark', width=950)

In [ ]:
X_train_pca[:5]

array([[-2.5124,  0.5993, -0.371 ],
       [-0.9918,  0.1528,  0.8572],
       [ 3.0099,  2.1686, -0.9938],
       [-1.0179,  0.081 ,  0.0923],
       [ 2.6792, -1.1157, -2.0518]])

In [ ]:
X_test_pca[:5]

array([[ 3.7158,  1.5134, -0.2131],
       [ 2.6902,  1.8935,  0.2028],
       [ 3.1346,  0.427 , -0.0083],
       [ 0.5666, -2.8499, -0.3972],
       [-0.4327, -3.394 , -0.3929]])